# TODO: remove this file by either moving cops here or fixing code
inherit_from:
  - https://raw.githubusercontent.com/theforeman/foreman/3.8-stable/.rubocop.yml

AllCops:
  Include:
    - 'app/views/api/**/*.rabl'
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Rails/Delegate:
  Enabled: false

# Don't prefer is_a? over kind_of?
Style/ClassCheck:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Performance/FixedSize:
  Exclude:
    - 'test/**/*'
