name: Assert Single Commit (non-blocking)

on: pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 30
    - name: Checkout main
      run: git fetch origin main
    - name: create local main branch
      run: git branch main origin/main
    - name: Commit Count Check
      run: test `git log  --oneline --no-merges HEAD ^main | wc -l ` = 1